// Every component with demo props, for visual QA (the `gallery` compositions). Demo data is simulated.
import { simBars } from "../lib/finance";
import simDemo from "../samples/sim-demo.json";

export interface GalleryEntry { name: string; component: string; props: Record<string, unknown>; secs?: number; note?: string }

export const GALLERY: GalleryEntry[] = [
  { name: "Mark (draw + snap)", component: "Mark", props: { size: 520, drawAt: 0.2 } },
  { name: "Lockup", component: "Lockup", props: { height: 150, drawAt: 0.2 } },
  { name: "ThePit", component: "ThePit", props: { lossPct: 0.5, note: "Same distance. Twice the percentage." } },
  { name: "ThePit · bedrock + dollars", component: "ThePit", props: { lossPct: 0.5, account: 10000, showBedrock: true } },
  { name: "ThePit · sweep + table", component: "ThePit", props: { lossPct: 0.9, fromLossPct: 0.1, showTable: true, sweepDur: 3, enter: false } },
  { name: "PitCurve", component: "PitCurve", props: { lossPct: 0.75, fromLossPct: 0.1 } },
  { name: "RCompare (same $500, two rulers)", component: "RCompare", props: { gain: 500, risks: [100, 2000], revealAt: 2.2 }, secs: 3 },
  { name: "RRuler (1R stamped up the chart)", component: "RRuler", props: { timeOffset: 8, measureAt: 8, ghost: { at: 13.2, from: 8.4 } }, secs: 8 },
  { name: "RTower", component: "RTower", props: { winRate: 0.35, avgWinR: 3, n: 20, seed: 7, label: "20 SIMULATED TRADES", convert: [{ label: "1% OF $10,000", risk: 100 }, { label: "1% OF $1,000,000", risk: 10000 }], convertAt: 3.2 } },
  { name: "Duel (win rate vs payoff)", component: "Duel", props: { step: 0.3 }, secs: 5 },
  { name: "Seesaw · fixed risk", component: "Seesaw", props: { account: 10000, accountRiskPct: 0.01, stopDistance: [1, 2, 4], hold: 1.6, startAt: 0.3 }, secs: 5 },
  { name: "Seesaw · fixed shares (tips)", component: "Seesaw", props: { mode: "shares", shares: 100, stopDistance: [1, 2, 4], hold: 1.3, startAt: 0.3 } },
  { name: "MarketWeather · tailwind", component: "MarketWeather", props: { regime: "tailwind", windStrength: 0.8, period: "SIMULATED" } },
  { name: "MarketWeather · storm", component: "MarketWeather", props: { regime: "storm", windStrength: 0.6, distributionDays: 6 } },
  { name: "TheRace", component: "TheRace", props: { dur: 3.5, window: "SIMULATED" } },
  { name: "Anatomy (synthetic VCP)", component: "Anatomy", props: { demo: true, revealSpeed: 22 }, secs: 5 },
  { name: "CandleChart + MAs + volume", component: "CandleChart", props: { bars: simBars(140, 5, 40, 0.003, 0.02), ma: [10, 21, 50], volume: true, revealDur: 3.5, measures: [{ from: 40, to: 70, fromPrice: "l", toPrice: "h" }], annotations: [{ at: 100, text: "Simulated", price: "h" }] }, secs: 5 },
  { name: "RunsFan (sims/risk_per_trade.py)", component: "RunsFan", props: { runs: simDemo["runs_2pct"], label: "RISK 2% PER TRADE · SIMULATED", dur: 3 } },
  { name: "Distribution", component: "Distribution", props: { values: simDemo.values["maxdd_2pct"], label: "MAX DRAWDOWN", badSide: "low" } },
  { name: "FiveExits", component: "FiveExits", props: { revealSpeed: 30 }, secs: 5 },
  { name: "Throttle", component: "Throttle", props: { leverage: 5, dur: 2.5 } },
  { name: "Hourglass", component: "Hourglass", props: { daysToExpiry: 60, iv: 0.3, dur: 3 } },
  { name: "Rope", component: "Rope", props: { dur: 3 } },
  { name: "PayoffDiagram · long call", component: "PayoffDiagram", props: {} },
  { name: "PayoffDiagram · short put", component: "PayoffDiagram", props: { legs: [{ type: "put", side: "short", strike: 100, premium: 3.2, iv: 0.3 }], underlyingRange: [70, 125] } },
  { name: "InnerChart", component: "InnerChart", props: { dur: 3 } },
  { name: "CouncilArc", component: "CouncilArc", props: { question: "Where does your stop go?", seats: [{ id: "a", name: "Seat A", emblem: "pivot-step", answer: "Demo answer: a paraphrase with a source." }, { id: "b", name: "Seat B", emblem: "cup-handle" }, { id: "c", name: "Seat C", emblem: "vcp" }, { id: "d", name: "Seat D", emblem: "stages" }, { id: "e", name: "Seat E", emblem: "shield" }], active: 0 } },
  { name: "LegendCard", component: "LegendCard", props: { legend: { no: "00", name: "Sample Legend", era: "1900s – 1950", markets: "Stocks", edge: "Demo field. Real cards are researched and sourced.", habit: "Demo field.", read: "Demo field." }, emblem: "diamond" } },
  { name: "PivotStep (pivotal point = tripwire)", component: "PivotStep", props: { drawDur: 3, adds: [560, 690] } },
  { name: "LegendTitle", component: "LegendTitle", props: { no: "00", name: "Sample Legend", years: "1900 – 1950", markets: "Stocks" } },
  { name: "FortuneLine (a career, sketched)", component: "FortuneLine", props: { events: [{ year: 1907, label: "DEMO WIN", kind: "win" }, { year: 1915, label: "DEMO LOSS", kind: "loss" }], reveal: { from: 1891, to: 1940, at: 0.2, dur: 3 } }, secs: 4 },
  { name: "TwinPaths (demo data)", component: "TwinPaths", props: { label: "DEMO · SIMULATED", twin: { paths: { "0.5pct": simBars(201, 3, 1, 0.001, 0.004).map((b) => b.c), "2pct": simBars(201, 3, 1, 0.004, 0.016).map((b) => b.c) }, maxdd: { "0.5pct": -0.05, "2pct": -0.2 }, final: { "0.5pct": 0.2, "2pct": 0.9 } }, dur: 3, ddAt: 3.2, finalAt: 3.4 }, secs: 4 },
  { name: "AverageDown (demo data)", component: "AverageDown", props: { title: "DEMO · SIMULATED PRICES", peakBefore: "2000-06-30", bars: simBars(200, 11, 50, -0.006, 0.04).map((b, i) => ({ t: new Date(Date.UTC(2000, 0, 7 + i * 7)).toISOString().slice(0, 10), c: b.c })), reveal: { from: "2000-01-01", to: "2003-12-31", at: 0.2, dur: 3 }, tellsAt: 3.3, stopAt: 3.6 }, secs: 4 },
  { name: "StopMap (two schools of stops)", component: "StopMap", props: {} },
  { name: "CupHandle (the pattern, named)", component: "CupHandle", props: { drawDur: 2.5, stopAt: 3 }, secs: 4 },
  { name: "Milestones", component: "Milestones", props: { title: "DEMO", items: [{ year: 1960, label: "First", at: 0.3 }, { year: 1975, label: "Second", sub: "A detail line", at: 1.2 }, { year: 1985, label: "Third", at: 2.0 }] } },
  { name: "ListCard", component: "ListCard", props: { label: "Demo list", items: [{ text: "A full, plain sentence.", sub: "Where it comes from." }, { text: "Another one." }, { text: "And a third." }], step: 0.6 } },
  { name: "RuleCard", component: "RuleCard", props: { text: "Keep the pit [[shallow]].", sub: "Small losses, short climbs." } },
  { name: "MythCard", component: "MythCard", props: { myth: "Down 50%? Up 50% gets it back.", fact: "Up 50% from $5,000 is [[$7,500]].", factAt: 1.4 } },
  { name: "PollCard", component: "PollCard", props: { question: "What would you do here?", options: ["Act on the break", "Wait for proof", "Pass"] } },
  { name: "TermCard", component: "TermCard", props: { term: "Expectancy", definition: "What you make or lose **per trade**, on average." } },
  { name: "QuoteCard", component: "QuoteCard", props: { text: "A paraphrase is labelled as one.", who: "Sample" } },
  { name: "StatCard", component: "StatCard", props: { value: 100, prefix: "+", suffix: "%", label: "to recover a 50% loss" } },
  { name: "AssumptionsPanel", component: "AssumptionsPanel", props: { items: ["1,000 runs, seed 7", "Each trade risks **1%**", "Wins pay 2R, losses cost 1R"] } },
  { name: "TitleCard", component: "TitleCard", props: { kicker: "Chapter 1", title: "The math of [[losses]]", sub: "Lore 001 · Lore 002 · Lore 003" } },
  { name: "EndCard", component: "EndCard", props: { lore_no: 1, next: { lore_no: 2, title: "35% winners can beat 60% winners" } } },
];
